"use client";
import { useId } from "react";

/** Page-unique id prefix (same approach as the kit's useGraphicPrefix). */
export function usePrefix(p = "bp") {
  return p + useId().replace(/[^a-zA-Z0-9_-]/g, "");
}
export const ref = (p: string, n: string) => `url(#${p}-${n})`;

/**
 * The kit's 3D gradient set and drop shadow (as in kit packages/icons/svg/*.svg, generated by
 * scripts/art.py), so the new barber art matches the kit icons.
 */
export function KitDefs({ p }: { p: string }) {
  return (
    <defs>
      <linearGradient id={`${p}-gold`} x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#FFF4B8" /><stop offset=".45" stopColor="#FFC93C" /><stop offset="1" stopColor="#F08C00" /></linearGradient>
      <linearGradient id={`${p}-peach`} x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#FFD9BF" /><stop offset=".5" stopColor="#FF8A4C" /><stop offset="1" stopColor="#E4572E" /></linearGradient>
      <linearGradient id={`${p}-lil`} x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#E7DDFF" /><stop offset=".5" stopColor="#9B7BFF" /><stop offset="1" stopColor="#5B3FD6" /></linearGradient>
      <linearGradient id={`${p}-mint`} x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#C9F7E1" /><stop offset=".5" stopColor="#34D399" /><stop offset="1" stopColor="#0E9F6E" /></linearGradient>
      <linearGradient id={`${p}-sky`} x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#D5EBFF" /><stop offset=".5" stopColor="#5FA8FF" /><stop offset="1" stopColor="#2563EB" /></linearGradient>
      <radialGradient id={`${p}-tyre`} cx=".42" cy=".38" r=".7"><stop offset="0" stopColor="#4A4E57" /><stop offset=".7" stopColor="#1B1D22" /><stop offset="1" stopColor="#060708" /></radialGradient>
      <radialGradient id={`${p}-rim`} cx=".35" cy=".3" r=".8"><stop offset="0" stopColor="#fff" /><stop offset=".5" stopColor="#D6DBE2" /><stop offset="1" stopColor="#7E8794" /></radialGradient>
      <linearGradient id={`${p}-chrome`} x1="0" y1="0" x2="1" y2="0"><stop offset="0" stopColor="#7E8794" /><stop offset=".35" stopColor="#fff" /><stop offset=".7" stopColor="#C9CED6" /><stop offset="1" stopColor="#7E8794" /></linearGradient>
      <filter id={`${p}-sh`} x="-30%" y="-30%" width="160%" height="170%"><feDropShadow dx="0" dy="2.5" stdDeviation="2.2" floodColor="#0A0A0A" floodOpacity=".22" /></filter>
    </defs>
  );
}
